artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data_source_URL: https://www.dropbox.com/scl/fi/yygtj4pn20onqebi9zbeu/train_data.zip?rlkey=xejca3z1s880obr1y7rks3e8z&st=jslqcrbr&dl=1
  val_data_source_URL: https://www.dropbox.com/scl/fi/i3h3mwsqwsedqi8jwy5d0/val_data.zip?rlkey=fobpijfq1zuu3ozosvvcfzc37&st=8syh7v71&dl=1
  test_data_source_URL: https://www.dropbox.com/scl/fi/t141qor6io98rrzzde2lv/test_data.zip?rlkey=dnelepg8b6ghxvrkiajwj56ht&st=0uimuo7s&dl=1
  local_train_data_file: artifacts/data_ingestion/train_data.zip
  local_val_data_file: artifacts/data_ingestion/val_data.zip
  local_test_data_file: artifacts/data_ingestion/test_data.zip
  unzip_train_dir: artifacts/data_ingestion/train
  unzip_val_dir: artifacts/data_ingestion/val
  unzip_test_dir: artifacts/data_ingestion/test



data_validation:
  image_dir: artifacts/data_ingestion/val  # Updated path for validation images
  labels: 
    - healthy
    - early_blight
    - late_blight
  batch_size: 100  # Batch size for processing images
  findings_output_file: artifacts/findings.txt  # Output file for validation findings



data_transformation:
  transformed_dir: artifacts/transformed_datasets
  unzip_train_dir: artifacts/data_ingestion/train
  unzip_val_dir: artifacts/data_ingestion/val
  unzip_test_dir: artifacts/data_ingestion/test




model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum_dataset
  model_ckpt: google/pegasus-cnn_dailymail




model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/model_trainer/pegasus-samsum-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv